<?php

return [
    \App\Models\Setting::WELCOME_HEADER =><<<STARTTEXT
<h1 style="text-align: center;"><span style="font-size: 24pt;">Welcome to</span></h1>
<p style="text-align: center;"><span style="font-size: 36pt;"><strong>UCryptoCash</strong></span></p>
STARTTEXT
,

    \App\Models\Setting::WELCOME_DESCRIPTION =><<<STARTTEXT
<p style="text-align: center;"><span style="font-family: 'Open Sans'; font-size: 16px; text-align: center;">Be a part of&nbsp;</span><span style="box-sizing: border-box; font-weight: bolder; font-family: 'Open Sans'; font-size: 16px; text-align: center;">UCryptoCash Exchange.</span><br style="box-sizing: border-box; color: #ffffff; font-family: 'Open Sans'; font-size: 16px; text-align: center; background-color: #370c1d;" /><span style="font-family: 'Open Sans'; font-size: 16px; text-align: center;">The best way to receive, send and trade cryptocurrency.</span></p>
STARTTEXT
,

    \App\Models\Setting::SECURED_DEAL_DESCRIPTION =><<<STARTTEXT
<p><span style="font-family: 'Open Sans'; font-size: 16px;">It is perfect way to make a deal with minimal risk.</span><br style="box-sizing: border-box; color: #d3d3d3; font-family: 'Open Sans'; font-size: 16px; background-color: #040e2c;" /><span style="font-family: 'Open Sans'; font-size: 16px;">You can buy and sell any goods with maximal safety, because your funds is protected by our rules.</span></p>
STARTTEXT
,

    \App\Models\Setting::TRADING_DESCRIPTION =><<<STARTTEXT
<p><span style="font-family: 'Open Sans'; font-size: 14.4px;">UCryptoCrash is a trusted platform for trading Bitcoins. The exchange provides fast order execution, low spread, and access to high liquidity orderbook for top currency pairs on the market. Cross-platform trading is realised via website, mobile app, and several API solutions. Safety of assets and data are backed by high security standards and advanced legal compliance.</span></p>
STARTTEXT
,

    \App\Models\Setting::PROTECTION_ADVANTAGE =><<<STARTTEXT
<p><span style="box-sizing: border-box; color: #5b6291; font-family: 'Open Sans'; font-size: 14.4px;">Our system is protected!</span><br style="box-sizing: border-box; color: #8693a7; font-family: 'Open Sans'; font-size: 14.4px; background-color: #00062b;" /><span style="color: #8693a7; font-family: 'Open Sans'; font-size: 14.4px;">We have been working since 2017 and during this period our system has never been hacked by intruders! All passwords, account data and user's personal data is protected by ComodoProtect&trade; and provides the highest degree of security in this industry! *</span><span class="text-danger" style="box-sizing: border-box; font-size: 12px; display: block; position: relative; font-family: 'Open Sans'; color: #dc3545 !important;">*In the midst of such projects</span></p>
STARTTEXT
,

    \App\Models\Setting::SAFETY_ADVANTAGE =><<<STARTTEXT
<p><span style="box-sizing: border-box; color: #5b6291; font-family: 'Open Sans'; font-size: 14.4px;">Our system is safe!</span><br style="box-sizing: border-box; color: #8693a7; font-family: 'Open Sans'; font-size: 14.4px; background-color: #01082b;" /><span style="color: #8693a7; font-family: 'Open Sans'; font-size: 14.4px;">We care about your safe and security of your assets, so we developed the GhLwork&trade; protection system, which provides holistic protection for your assets. We transmit all data with safe httpS:// protocol, and nobody can get access to your account, because of using Two-Factor-Authentification.</span></p>
STARTTEXT
,

    \App\Models\Setting::SUPPORT_ADVANTAGE =><<<STARTTEXT
<p><span style="box-sizing: border-box; color: #5b6291; font-family: 'Open Sans'; font-size: 14.4px;">We are always online</span><br style="box-sizing: border-box; color: #8693a7; font-family: 'Open Sans'; font-size: 14.4px; background-color: #00062b;" /><span style="color: #8693a7; font-family: 'Open Sans'; font-size: 14.4px;">To make use of the site as comfortable as possible, as we can for our customers, we hired a support group - these are specially trained people who will answer any question! Our website support team works round-the-clock, 7 days a week to answer any your questions! To write to support just click on the widget at the bottom of the site!</span></p>
STARTTEXT
,

    \App\Models\Setting::STABILITY_ADVANTAGE =><<<STARTTEXT
<p><span style="box-sizing: border-box; color: #5b6291; font-family: 'Open Sans'; font-size: 14.4px;">Our system is stable!</span><br style="box-sizing: border-box; color: #8693a7; font-family: 'Open Sans'; font-size: 14.4px; background-color: #00062b;" /><span style="color: #8693a7; font-family: 'Open Sans'; font-size: 14.4px;">We've eliminated all the factors that could interfere with our system. We are working since 2017 and during this time we have repeatedly confirmed our competence in the market of cryptocurrencies!</span></p>
STARTTEXT
,

    \App\Models\Setting::ADDRESS => "110 Bishopsgate, London EC2N 4AD, UK",
    \App\Models\Setting::EMAIL => "support@gmail.com",

    \App\Models\Setting::ABOUT =><<<STARTTEXT
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">Chartrade company begins its history from July 2017, when it was developed and registered by our founder - Jaxon Strickland and his team.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">Our company has come a long way from a simple exchange platform to a complex mechanism, which works smoothly.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">We have changed the perception of many people about cryptocurrency and its use.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">We introduced lots of interesting and useful technologies, which are helping us to protect your funds, and helping you to invest your funds with maximum benefit.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">World's first we created system, which helps you to buy, sell, transfer your funds inside our exchange in few seconds, you don't need to wait blockchain confirmation any more. In our Exchange your funds This one, and lots of another features makes trading in Chartrade Exchange very comfortable, useful and profitable.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">After making a deposit, your funds constantly are stored on the permanent wallet, no matter what manipulations you do with them. They are assigned to you in the internal system of our site, so you shouldn't pay a commission on the blockchain network during transfer, trading and other transactions.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">We are interested in cryptocurrencies and we believe they will change the world and become the main currency in the future.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">We believe that cryptocurrencies will continue to grow and develop tirelessly, so we offer to invest in them right now, because even a very small investment changes the world.</span></p>
<div class="why" style="box-sizing: border-box; margin-bottom: 70px; color: #212529; font-family: 'Open Sans'; font-size: 14.4px;">
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff;"><span style="box-sizing: border-box; font-weight: bolder; background-color: #900909;">Why is it necessary to invest in such currencies?</span></p>
<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; margin-left: 40px;">
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">This excludes banks from the money exchange chain between stores and users, which significantly reduces the percentage of fees.</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">Cryptocurrencies are anonymous, it is need, because when you are living in the 21st century, nobody can guarantee you 100% privacy. Your phone, your camera on your laptop, your speakers - all of this takes away from you your privacy, despite only you are owner of this information! In financial world only cryptocurrencies, thanks to their unique technology, can provide you anonymity and privacy.</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">It's easy! By us, buying and selling cryptocurrencies has become much easier, which simplifies the work.</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">It's profitable! Many people have earned lots of money in trading! Just become a part of these people!</span></li>
</ul>
</div>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">Sincerely yours,</span><br style="box-sizing: border-box;" /><span style="background-color: #900909;"><span style="box-sizing: border-box; font-weight: bolder;">UCryptoCash</span>&nbsp;and our team.</span></p>
STARTTEXT
,

    \App\Models\Setting::USER_AGREEMENT =><<<STARTTEXT
<p><span class="h5 th" style="box-sizing: border-box; color: #ffffff; margin-bottom: 55px; font-weight: bold; line-height: 1.2; font-size: 20px; display: block; margin-top: 0px; font-family: 'Open Sans'; background-color: #900909;">THANK YOU FOR CHOOSING https://ucryptocash.com.com (the "Site").</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">This User Agreement is an electronic agreement between you (hereinafter the &ldquo;User&rdquo;) and https://ucryptocash.com Finance LLP, a company registered and operating according to the laws of England and Wales, Company number OC393265, with the registered address 110 Bishopsgate, London EC2N 4AD, UK (hereinafter the &ldquo;https://ucryptocash.com&rdquo;) that applies to your use of this website, all services, products and content provided by https://ucryptocash.com.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">The text of this Agreement permanently located at&nbsp;<a class="link" style="box-sizing: border-box; color: #5b6291; text-decoration-line: none; background-color: #900909;" href="../../terms-and-conditions">https://ucryptocash.com/terms-and-conditions</a>&nbsp;contains all the essential conditions of the public offer of https://ucryptocash.com. By creating an account on the Site or by using any of the Services, you acknowledge that you have read, understand, and completely agree to this Agreement in effect from time to time.</span></p>
<p class="h5 pr" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 16px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">THE PRESENT OFFER IS CONSIDERED TO HAVE BEEN ACCEPTED PROPERLY IF THE USER FOLLOWS THE STEPS LISTED BELOW:</span></p>
<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; margin-left: 40px; color: #212529; font-family: 'Open Sans'; font-size: 14.4px;">
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">GET FAMILIARIZED WITH THE CONDITIONS OF THIS USER AGREEMENT AND ALL ITS SUPPLEMENTS;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">INTRODUCE REAL AND ACTUAL INFORMATION INCLUDING AUTHENTIC LOGIN, EMAIL AND PASSWORD AS WELL AS ENTER THE CAPTCHA CODE INTO THE REGISTRATION FORM IN THE &lsquo;REGISTER&rsquo; TAB LOCATED AT&nbsp;<a class="link" style="box-sizing: border-box; color: #5b6291; text-decoration-line: none; background-color: #900909;" href="../../terms-and-conditions">https://ucryptocash.com.COM/</a>;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">PUT THE REQUIRED SYMBOL IN THE SPECIAL BOX BELOW THE TITLE &lsquo;I ACCEPT THE CONDITIONS OF THE AGREEMENT&rsquo; IN THE REGISTRATION FORM;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">PRESS THE &lsquo;CONTINUE&rsquo; BUTTON AFTER FILLING THE REGISTRATION FORM.</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">AFTER THE USER PRESSES THE &lsquo;CONTINUE&rsquo; BUTTON AND SEE APPEARED THE SPECIAL MESSAGE INFORMING ABOUT THE SUCCESSFUL REGISTRATION, THE REGISTRATION PROCESS IS CONSIDERED COMPLETED AND THE CONDITIONS OF THE PRESENT USER AGREEMENT BECOME OBLIGATORY TO ABIDE FOR THE REGISTERED PERSON.</span></li>
</ul>
<p class="at" style="box-sizing: border-box; margin-top: 50px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;"><span class="attention" style="box-sizing: border-box; color: red;">ATTENTION:</span>&nbsp;IF YOU DO NOT AGREE WITH THE CONDITIONS OF THIS USER AGREEMENT, PLEASE DO NOT REGISTER ON THE WEB&nbsp;<a class="link" style="box-sizing: border-box; color: #5b6291; text-decoration-line: none; background-color: #900909;" href="../../terms-and-conditions">https://ucryptocash.com</a>&nbsp;AND DO NOT USE ITS SERVICE.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">UCryptoCash and the third party using the site in the Internet network located at&nbsp;<a class="link" style="box-sizing: border-box; color: #5b6291; text-decoration-line: none; background-color: #900909;" href="../../terms-and-conditions">https://ucryptocash.com</a>&nbsp;have concluded the present Agreement on the following conditions.</span></p>
STARTTEXT
,
    \App\Models\Setting::USER_AGREEMENT_POINTS =><<<STARTTEXT
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">1. TERMS AND DEFINITIONS</span></p>
<p><span style="background-color: #900909;"><span style="box-sizing: border-box; font-weight: bolder; font-size: 16px; color: #d3d3d3; font-family: 'Open Sans'; background-color: #900909;">In the present Agreement the following terms have the meaning indicated below, unless otherwise is stipulated:</span></span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.1. Agreement means the present User Agreement.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.2. Account means functional part of the System that controls User&rsquo;s Funds and operations conducted with them. 1.3. Anti-Money Laundering Policy means program on prevention of laundering of money derived from criminal activity and financing of terrorism, which constitutes an essential part of the Agreement which text is available at https://https://ucryptocash.com.com/en/docs/aml.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.3. Chat means the System's function intended for instant messaging between the Users.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.4. Cryptocurrency means peer-to-peer digital currency that has no central issuer and is distributed directly between the owners of such currency.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.5. Deal means agreement on onerous alienation of rights on Cryptocurrency concluded between the Users of UCryptoCash.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.6. Deposit means a transaction involving a transfer of Funds to the Account.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.7. https://ucryptocash.com is https://ucryptocash.com Finance LLP, a legal entity registered according to the law of UK, with the registration number OC393265 of the 19th of May, 2014 , with registered address at 110 Bishopsgate, London EC2N 4AD, UK including but not limited by employees, officers, directors and shareholders, affiliated persons of https://ucryptocash.com Finance LLP. Depending on the context https://ucryptocash.com also may mean services, products, web-sites, content and other materials, provided by https://ucryptocash.com.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.8. Exchange Rate means relation between the amount of Funds and the price offered by the User for Deals of exchanging Funds. 1.10. Fees mean rewards payed to UCryptoCash by the parties of deals and the prices for additional services rendered by https://ucryptocash.com constantly available at https://https://ucryptocash.com.com/en/docs/fees/.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.9. Fiat money means government-issued currency, that is designated as legal tender in its country of issuance on the legislative level.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.10. Funds means Fiat money and Cryptocurrency used during the execution of Deals.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.11. Margin Deal means deal executed with the use of the Funds provided by to the Client in returned and refundable use.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.12. Margin Level means the amount of Funds in the User Account necessary for execution of a Margin Deal expressed in a percentage ratio to the amount of Funds provided to the User.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.13. Order means User's offer to close a Deal on certain conditions.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.14. Parties means https://ucryptocash.com and the User.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.15. Personal Cabinet means set of protected pages created as a result of the User registration in the System, using which the User can to place Orders for further execution of Deals as well as instruct the https://ucryptocash.com commissions stipulated by the present Agreement. The Personal Cabinet reflects information about placed and cancelled Orders, closed Deals, available funds and/or Cryptocurrency and other information determined by the functions of the Site.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.16. Privacy Policy means rules of collection, storage, distribution and protection of personal data that the https://ucryptocash.com gets from the Users and that is an essential part of the Agreement which text is available at https://https://ucryptocash.com.com/en/docs/privacy_policy/.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.17. Site means set of information, texts, graphic and design elements, pictures, photo, video and other fruits of intellectual activity, as well as set of computer programs contained in the information system which ensures the accessibility of this information at https://https://ucryptocash.com.com.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.18. Services mean all and any service provided by https://ucryptocash.com.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.19. System means set of software and technical means used by the https://ucryptocash.com in automatic mode to process operations conducted by the User in his/her Personal Cabinet.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.20. User means сapable under personal law natural person or business entity formatted in the appropriate legal form according to local legislation that use the Site and/or the System and has concluded the corresponding Agreement with https://ucryptocash.com.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.21. User Account Data means User Data necessary to access and use the System &ndash; login, password, email and other data indicated during the registration process as well as after it.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.22. Withdrawal means a transaction involving a transfer of Funds from the User&rsquo;s Account.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.23. Stopout - forced closure of trading position at a market price, in order to protect the financial interests of participants in the Marginal Deal from the negative balance of the Account.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">1.24. Leverage is the ratio of the User's own funds to the volume of trading operations that it can perform at the expense of the Funds granted to it under a Loan agreement. The rest of terms and definitions that can be found in the text of the Agreement should be interpreted by the Parties according to the legislation of the UK and to the general rules of interpretation of such terms accepted in the Internet network. The titles of different sections (articles) of the Agreement have been put with the only objective to make the text more comfortable for the reader and do not have any literal legal effect.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">2. SUBJECT OF THE AGREEMENT</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">2.1. Under the Agreement https://ucryptocash.com renders to the User the following services:</span></p>
<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: 'Open Sans'; font-size: 14.4px;">
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">grants access to the System in order to carry out Deals;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">grants access to the Account within the System;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">gives the possibility to carry out Margin deals;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">provides information necessary for the use of the System and carrying out Deals.</span></li>
</ul>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">2.2. Depending on the User&rsquo;s place of residence, the User may not be able to use all the functions of the Site. It is the User&rsquo;s responsibility to follow those rules and laws in his/her place of residence and/or place from which the User accesses this Site.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">2.3. The User acknowledges and agrees that, when completing Trading Transactions, he/she is trading with other User, and that https://ucryptocash.com is not a counterparty to any trade.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">2.4. Essential parts of the present Agreement are sections dedicated to Privacy policy, Anti-Money Laundering Policy, and the Fees.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">3. ACCESS TO THE SYSTEM, REGISTRATION PROCESS AND CHAT USE</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">3.1. https://ucryptocash.com grants the User access to the information about the System, Currency Rates offered by other Users, closed Deals and about placed Orders before the registration process is completed.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">3.2. In order to get access to the System, the User should complete the registration process. After that the User will get access to the Personal Cabinet created on the basis of the User Account Data.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">3.3. The User is responsible for setting up a password during the registration process. The User can change the password any time after the registration process is completed. The User commits to safeguard password and User Account Data from the access of third parties and is the one to determine the best way to save this data and take steps to prevent it from being discredited. In case of loss or discrediting the password and/or the User Account Data as well as in cases when third parties illegally obtain access to the User&rsquo;s Personal Cabinet, the User has to inform the https://ucryptocash.com about these circumstances by contacting the technical support team (support{{ config('app.url') }}.com). Until https://ucryptocash.com receives the corresponding message, all the actions made from the User Personal Cabinet will be considered as made by the proper User as the holder of the Account.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">3.4. The User has the right to hold and use only one Personal Cabinet and cannot use two or more Personal Cabinets. Such actions will be considered as violation of this Agreement.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">3.5. The User gets access to the Chat after replenishing the Account with the sum equal to or exceeding 500,00 (five hundred) USD regardless of the kind of Funds. While using the Chat, the User is prohibited to:</span></p>
<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: 'Open Sans'; font-size: 14.4px;">
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">insult and threaten other users and/or https://ucryptocash.com staff. This is considered as a direct violation of the rules of chat use and may result in a permanent ban of the User; - use any forms of obscene language;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">make statements stirring up to international dissention, containing violence propaganda or offending religious feelings of other Users;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">send any kind of external links;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">text messages in capital letters only;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">repeatedly text the same information or constantly repeat the same phrase;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">offer to buy or sell the Funds;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">advertise products or services of other companies;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">flood, spam and discuss topics that are not related to cryptocurrency or the exchange;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">providing false or misleading information about exchange.</span></li>
</ul>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">4. THE ACCOUNT</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.1. After registration in the System the User gets access to his/her Account in the Personal Cabinet. The User can operate personally using his/her Account and the Personal Cabinet as well as instruct the System to execute operations with their Account automatically.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.2. The https://ucryptocash.com indicates in the Personal Cabinet the information necessary for the replenishment of the Account and for the withdrawal of Funds from the Account.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.3. To replenish the Account the User has to transfer Funds according to the bank details indicated by https://ucryptocash.com in the User Personal Cabinet. The User is responsible for paying commissions and service fees related to the transfer as well as assumes the risks of indicating an incorrect bank account details.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.4. The Account is considered to be replenished when the corresponding amount of money enters the current account of https://ucryptocash.com or when a corresponding message appears in the https://ucryptocash.com wallet about receiving not less than 6 (six) confirmations.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.5. The https://ucryptocash.com commits to receive Cryptocurrency items from Users, keep them, keep a record of them, execute transactions and provide them to the the Users upon their request.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.6. The https://ucryptocash.com keeps a record of the funds transferred to the Account and does not keep Users&rsquo; money. Money transfers during the Account replenishment as well while executing Deals between the Users are carried out by third parties (aggregators, payment institutions and other facilitators). The https://ucryptocash.com is not liable for actions of these third parties.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.7. All Account operations are carried out at User&rsquo;s request. The https://ucryptocash.com does not accept orders on carrying out any operation with the User Account from third persons except otherwise is stipulated by the Agreement or other agreements between the Parties.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.8. All the Funds placed on the Account belong to the User. The https://ucryptocash.com cannot block Funds on the Account without the order emitted by the User as well as can write-off Funds only in cases stipulated by the Agreement.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.9. Interests do not apply to the remainder amount of Funds in the User Account, and the https://ucryptocash.com is not committed to pay the abovementioned interests.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.10. To withdraw Funds from the Account, the User has to fill the corresponding form in their Personal Cabinet. The User will get a message to the email address indicated during the registration process asking to confirm or to deny the withdrawal operation. In case the User denies or does not confirm the withdrawal, the Funds will remain in the Account, but it will happens only after User fulfill all the conditions, which is written in this Agreement.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.11. The System sets some restrictions for Funds withdrawals and the User cannot instigate withdraw Funds during 3 (three) days after changing User Account Data, which includes changing or restoring password, and also changing authorization method.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.12. The User acknowledges and agrees that Deposit and Withdrawal Transaction in Fiat currency may be delayed due to bank verifications and checks, for a period up to one (1) month. Similarly and due to the inherent nature of the cryptocurrency networks, the User acknowledges and agrees that depositing and withdrawing Cryptocurrencies into/from his/her Account may take between one (1) hour and seventy two (72) hours, barring unforeseen or unavoidable network issues.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.13. In case if the User discovers suspicious transaction activity, including but not limited to unknown deposits and withdrawals, on his/her Account that was not initiated by the User, the User shall immediately notify https://ucryptocash.com of this fact and follow the instructions sent by https://ucryptocash.com. Otherwise, https://ucryptocash.com reserves the right to freeze the Account until the end of investigation.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.14. https://ucryptocash.com may be forced to cancel or recall already executed Withdrawal Transaction at a request of financial institutions, including but not limited to banks, which are involved in settlement related to deposit and withdrawal of Funds from User`s Accounts. In such cases the User is obliged to cooperate with https://ucryptocash.com in order to discover the reasons for such request.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.15 If User want to buy premium account to use trading, he should be noticed, that we take 2.5% fee from that deposit, which is maden for purchasing a premium status for his account.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.16 If registration term of User's account is less then 1 month, and he received more than 15 BTC or the same value in other currencies - he should buy VIP account. Until he make this purchasing his account should be limited in withdrawing. Usual price of VIP account is 0.5 BTC or the same value in other currencies.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">4.17 Creating multi-account is forbidden. One User - one account. In case if our system identify multi-account, account with less balance will be banned. User should pay the penalty for creating multi-account. The amount of this penalty is 0.25 BTC.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">5. TRADING DEALS</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6. TYPES OF ORDERS</span></p>
<p><span style="background-color: #900909;"><span style="box-sizing: border-box; font-weight: bolder; font-size: 16px; color: #d3d3d3; font-family: 'Open Sans'; background-color: #900909;">6.1. Simple buy order</span></span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.1.1. A simple buy Order represents the User&rsquo;s offer to buy a certain amount of Funds at the Exchange Rate set by the User.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.1.2. To place a simple buy Order the User has to fill the corresponding form in the Personal Cabinet indicating the amount of Funds to buy and setting the Exchange Rate.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.1.3. A simple buy Order can be executed at a lower Exchange Rate than the one indicated in the placed Order. Herewith the User will be refunded with the excessively paid part of the commission. A simple buy Order cannot be executed at a higher Exchange Rate than the one indicated in the placed Order.</span></p>
<p><span style="background-color: #900909;"><span style="box-sizing: border-box; font-weight: bolder; font-size: 16px; color: #d3d3d3; font-family: 'Open Sans'; background-color: #900909;">6.2. Simple sell Order</span></span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.2.1. A simple sell Order represents the User&rsquo;s offer to sell a certain amount of Funds at the Exchange Rate set by the User.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.2.2. To place a simple sell Order the User has to fill the corresponding form in the Personal Cabinet indicating the amount of Funds to sell and setting the Exchange Rate.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.2.3. When placing a simple sell Order the User has the possibility to use additional functions of the System like &lsquo;Stop Loss&rsquo; or &lsquo;Trailing Stop&rsquo;. Marking a special box opposite the corresponding field in the form for placing a simple sell Order is considered the ground for using these functions.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.2.4. To use &lsquo;Stop Limit&rsquo; the User has to indicate in the form the minimum price at which the Order can be executed. If the System Exchange Rate falls the placed Order will be executed when reaches the value indicated by the User in the box &lsquo;Stop Loss&rsquo;.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.2.5. To use &lsquo;Trailing Stop&rsquo; the User has to indicate in the form the amount of Funds to sell as well as &lsquo;Trailing Stop&rsquo; and &lsquo;Stop Limit&rsquo; values. The Funds will be offered for sale at a highest current Exchange Rate determined by the System. If the System Exchange Rate starts to raise and will increment by the value indicated in the box &lsquo;Trailing Stop&rsquo;, the Exchange Rate for the Order placed by the User will increment by a corresponding amount. Herewith &lsquo;Stop Loss&rsquo; index will increment by the amount indicated in the box &lsquo;Trailing Stop&rsquo;.</span></p>
<p><span style="background-color: #900909;"><span style="box-sizing: border-box; font-weight: bolder; font-size: 16px; color: #d3d3d3; font-family: 'Open Sans'; background-color: #900909;">6.3. Market buy Order</span></span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.3.1. A market buy Order represents the User&rsquo;s offer to buy a certain amount of Funds without setting the Exchange Rate.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.3.2. To place a market buy Order the User has to fill the corresponding form in the Personal Cabinet indicating the amount of Funds to buy.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.3.3. The Order will be executed at the lowest Exchange Rate found among the Orders placed by other Users.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.3.4. The https://ucryptocash.com reward for the operation will be charged immediately at the moment of Deal closure.</span></p>
<p><span style="background-color: #900909;"><span style="box-sizing: border-box; font-weight: bolder; font-size: 16px; color: #d3d3d3; font-family: 'Open Sans'; background-color: #900909;">6.4. Market sell Order</span></span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.4.1. A market sell Order represents the User&rsquo;s offer to sell a certain amount of Funds without setting the Exchange Rate.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.4.2. To place a market sell Order the User has to fill the corresponding form in the Personal Cabinet indicating the amount of Funds to sell.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.4.3. The Order will be executed at the highest Exchange Rate found among the Orders placed by other Users.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.4.4. The https://ucryptocash.com reward for the operation will be charged immediately at the moment of Deal closure.</span></p>
<p><span style="background-color: #900909;"><span style="box-sizing: border-box; font-weight: bolder; font-size: 16px; color: #d3d3d3; font-family: 'Open Sans'; background-color: #900909;">6.5. Complex buy and sell Order</span></span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.5.1. A complex buy and sell Order represents the User&rsquo;s offer to buy a certain amount of Funds at the Exchange Rate set by the User and to sell the acquired amount of Funds at the Exchange Rate set by the User. So, when the User places a complex buy and sell Order, the System in its turn places firstly a simple buy Order and when it is executed, places a simple sell Order.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.5.2. To place a complex buy and sell Order the User has to fill the corresponding form in the Personal Cabinet indicating the amount of Funds to buy and setting the Exchange Rate as well as setting the Exchange Rate to be used during the sale of the acquired Funds.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">6.5.3. This type of Order is governed by a set of rules elaborated for simple buy Order and simple sell Order with specificities related to complex buy and sell Order.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">7. MARGIN DEALS</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.1. In certain cases stipulated by the Agreement the https://ucryptocash.com gives the User a possibility to make a Margin Deal.</span></p>
<p><span style="background-color: #900909;"><span style="box-sizing: border-box; font-weight: bolder; font-size: 16px; color: #d3d3d3; font-family: 'Open Sans'; background-color: #900909;">7.2. It is possible to make a Margin Deal using the following Order types:</span></span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.2.1. Simple sell Order;</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.2.2. Simple buy Order;</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.2.3. Complex buy and sell Order but only during the purchase phase.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.3. Providing of any actions envisaged by the System's functionality aimed at concluding a Marginal Deal (marking in the "Loan"/ "Take a Loan" field, etc.) means the User's consent to the conditions for the implementation of Marginal Transactions.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.4. The loan agreement is considered concluded from the moment of crediting of Funds to the Account of the User.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.5. The funds are provided to Users on a refundable and onerous basis.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.6. The User should have the necessary margin Level on their Account in order to make a Margin Deal.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.7. Margin Level amounts to 100% (one hundred percent) of the amount of provided Funds for the Margin Deal. Margin Level can be changed at the agreement with the https://ucryptocash.com but cannot be lower than 25% (twenty five percent) of the amount of provided Funds.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.8. In case the Margin Deal is closed on the parameters set by the User in the placed Order, the System writes off the User Account the amount of Funds equivalent to the amount of Funds provided on the basis of loan agreement as well as the corresponding commission. The amount of commission is determined by the Fees.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.9. In case the User acquires a debt as a result of making a Margin Deal, the https://ucryptocash.com has the right to restrict the use of Personal Cabinet until the User replenishes his/her Account for a sum equivalent to the amount of the debt. Herewith the User is obliged to replenish the corresponding Account during 5 (five) working days from the moment of acquiring these liabilities.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.10. In case of risk that the Margin Level on the User Account can result insufficient, the https://ucryptocash.com has the right, at sole discretion and without previously notifying the User, to decide on the immediate execution of the Order or call it back. The above mentioned actions are not considered as a violation of obligations on behalf of the https://ucryptocash.com.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.11. The User agrees that https://ucryptocash.com has the right to execute a stop-loss at a Margin Level of less than 30% at a 1: 2 leverage, and this action is not a violation of the obligations of https://ucryptocash.com.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">7.12. Tracking changes in the conditions for execution of Marginal transactions and compliance with the performance of margin requirements is a direct duty of the client. https://ucryptocash.com is not liable for any losses that may result from a lack of information or untimely disclosure of the margin requirement. https://ucryptocash.com does not have to inform the User in any way about the execution of the stop-loss (s), or about the sale or liquidation of the User's Funds from his Account in the System, if such account is not replenished as a result of arrears.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">8. DETECTION AND PREVENTION OF ILLEGAL SITE AND SYSTEM USE</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">8.1. The User is prohibited to conduct Deals omitting the formal procedure of placing Orders by means of using personal messages and other options of the Site and/or the System. In these cases a message ceases to be private and becomes available for moderators and the administration if one of chat users complaints about it.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">8.2. The User is prohibited to use the Site and/or the System in any other way than those stipulated in the Agreement; in particular, the User is not allowed to advertise products on the Site in case the Parties have not entered an additional specific agreement.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">8.3. The User is prohibited to use the Site and/or the System with unlawful aims including laundering of money derived from criminal activity, financing of terrorism and involvement in extremist activity.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">8.4. The User is obliged to go through the identification process established by the System or third parties (aggregators, credit or other organs) during the Deal-making process as well as fulfill the requirements stipulated by UK law in the field of counteraction of laundering (legitimization) proceeds of crime.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">9. RISK WARNING</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">9.1. The User guarantees that he/she understands general principles of work with Cryptocurrencies and is aware of Cryptocurrency of the following characteristics affecting its value and risks related to it:</span></p>
<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: 'Open Sans'; font-size: 14.4px;">
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">Price volatility: The value of cryptocurrencies is extremely volatile. They are vulnerable to sharp changes in price due to unexpected events or changes in market sentiment.</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">Leverage: Leverage multiplies User&rsquo;s profits but also potential losses and can have a significant impact on fees. It also places User at risk of losing more than his/her initial investment.</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">Charges and funding costs: Charges and Fees can include the spread, funding charges, and commissions.</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">Price transparency: When compared with fiat currencies, there can be more significant variations in the pricing of cryptocurrencies used to determine the value of User&rsquo;s position. There is a greater risk that the User will not receive a fair and accurate price for the underlying cryptocurrency when trading.</span></li>
</ul>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">9.2. User should only participate in trading deals if he/she has a sophisticated knowledge of financial markets and fully understands the risks associated with cryptocurrencies.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">9.3. The User guarantees that he/she has a right to execute transactions with Cryptocurrency and possesses a full legal capacity.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">9.4. The User understands that the https://ucryptocash.com in no way influences the Exchange Rate set by the Users, does not give recommendations on Exchange Rate determination and does not forecast the rates. The User is responsible for all economic risks related to choosing particular Exchange Rate. The https://ucryptocash.com does not guarantee that the Deal will be finally closed and that the conditions of this Deal will be of the User&rsquo;s benefit.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">9.5. The User understands that the https://ucryptocash.com in no way bears relation to deal conduction and/or transactions related to Cryptocurrency. Correspondingly the https://ucryptocash.com does not assume the responsibility to guarantee terms and/or possibilities of carrying out this or that operation and/or transaction related to Cryptocurrency, which are necessary for Deal making.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">9.6. The User understands that all the operations with Cryptocurrency have irreversible character and that Funds acquired during the Deal can be returned only on the basis of additional specific agreement with other User.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">10. INTELLECTUAL PROPERTY AND RESTRICTIONS ON SITE AND SYSTEM USE</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">10.1. The Site and the System contain fruits of intellectual labor that belong to the https://ucryptocash.com, affiliated persons and other related parties, sponsors, partners, representatives, all the parties acting on behalf of the https://ucryptocash.com and other third parties.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">10.2. By using the Site and the System the User acknowledges and agrees that all Site content and the structure of Site content are protected by copyright, trademark and other rights concerning the results of intellectual activity, and that the abovementioned rights are authentic and are protected in their every form, in all carriers and regarding all existing and created later technologies. No rights as well as no Site nor System content are committed to the User as a result of Site and System use or on the conclusion of the Agreement.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">10.3. To avoid any misunderstanding the User is prohibited to:</span></p>
<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: 'Open Sans'; font-size: 14.4px;">
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">copy and/or diffuse any items of intellectual property published on the Site and/or in the System except when this function is clearly contemplated by the Site and/or the System;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">copy or use in any other way the program part of the Site and/or the System as well as its design;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">diffuse on the Site and/or in the System personal data of third persons without their permission;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">change in any way the program part of the Site and/or the System, take any actions aimed at changing the functionality and operability of the Site and/or the System;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">use insults or any words violating rights and liberties of third persons as a login (nickname, alias) during the registration.</span></li>
</ul>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">11. RESPONSIBILITIES OF THE PARTIES</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">11.1. In case the User violates the conditions of the present Agreement, the legislation of the UK, morality norms or in case he/she conspires with another User to violate the conditions of the Agreement, the https://ucryptocash.com will have the right to block or delete the User&rsquo;s Personal Cabinet, prohibit or restrict their access to certain or all functions of the System using his/her Personal Cabinet.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">11.2. In case the User violates the terms of the return of Funds provided under the Marginal Deal, https://ucryptocash.com is entitled to demand from the User payment of a penalty amounted to 1% (one percent) of the Funds provided to the User for each day of delay.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">11.3. If the https://ucryptocash.com detects that the User has violated paragraph 8 of the present Agreement, the https://ucryptocash.com will have the right to delete the User&rsquo;s Personal Cabinet and demand indemnity for losses.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">11.4. The https://ucryptocash.com is not responsible for the operability of the Site and/or the System and does not guarantee its continuous operation. The https://ucryptocash.com does not guarantee the safety of the information published on the Site and/or in the System as well as does not guarantee the possibility of continuous access to the information about Orders and closed Deals, the possibility of Order placement and of making Deals.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">11.5. The User uses the Site and the System in its original form at his/her own risk. The https://ucryptocash.com does not guarantee the achievement of any results by the User owing to the Site and/or System use.11.6. The https://ucryptocash.com does not guarantee that the Site and the System satisfy the requirements of the User as well as does not guarantee continuous, fast, save and error-free access to the Site and/or the System.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">11.6. The https://ucryptocash.com does not guarantee that the Site and the System satisfy the requirements of the User as well as does not guarantee continuous, fast, save and error-free access to the Site and/or the System.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">12. SPECIAL CONDITIONS</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.1. The Site and the System can contain external links to other sites in the Internet network (third parties&rsquo; sites). The abovementioned third parties&rsquo; sites and their content are not checked by criteria of conformity with certain requirements (authenticity, completeness, legality, etc.). The https://ucryptocash.com will not be liable for the information and the materials published on third parties&rsquo; sites, which the User can access via the Site and/or the System as well as does not assume any responsibility for expressed opinions or statements, advertising materials, the accessibility and possible consequences of use of third parties&rsquo; sites.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.2. The https://ucryptocash.com has the right to transfer rights and debts under all obligations derived from the Agreement. By accepting the present Agreement the User gives their consent on transferring rights and debts to any third party. In case of rights and/or debts are transferred, the https://ucryptocash.com will inform the User about it leaving the corresponding message on the Site and/or in the System.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.3. Given the specifics of transactions, https://ucryptocash.com does not implement a chargeback policy. However, https://ucryptocash.com has developed and implemented a detailed Cross-Chain Recovery Policy, which provides a detailed guideline in the cases where an erroneous deposit of one cryptocurrency into wallet address instead of another cryptocurrency is made by the User. The recovery of Cross-chain deposits is an inherently dangerous and a very time consuming process. Not all deposits can be recovered and dependent on which currency has been mistakenly sent to which address can influence difficulty, time and security risk involved.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.4. Making a transaction, the User agrees and carries the entire risk on the transaction. To https://ucryptocash.com cannot be made any claims for the cancellation of the Transaction. https://ucryptocash.com does not accept or process applications from anyone for the return and / or cancellation of an operation. The Exchange take 1% fee from ever deposit.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.5. Withdrawing is carried funds from cryptocurrency wallets of our exchange to other cryptocurrency wallets that are not part of our exchange and are in the explotation of other payment systems after the procedures of verification of ownership of the corresponding crypto-wallet to the corresponding user on the right of ownership, and synchronization of our exchange with the cryptocurrency wallet to which the User whants to withdraw funds.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.5.1 Verification of cryptocurrencies is carried out in order to exclude the possibility of illegal use of funds contained in the account of the user of our exchange.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.5.1.1 Verification of crypto-wallets is carried out in the following order:</span></p>
<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: 'Open Sans'; font-size: 14.4px;">
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">Creation of a deposit application;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">Witdrawing the verified cryptocurrency wallet in the declared amount according to the commission terms established by the Parties.</span></li>
</ul>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.5.2. Synchronization cryptocell is carried out with the aim of eliminating the possibility of creating users accounts, and the provision of certainly not truthful personal data.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.5.2.1. Synchronization of cryptocurrency wallets is carried out in the following order:</span></p>
<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: 'Open Sans'; font-size: 14.4px;">
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">Installation of the Chrome&trade; browser extension and other browsers on the Chromium&trade; system.</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">Authorization on the site, part of which is the cryptocurrency wallet to which the User intends to withdraw their funds.</span></li>
</ul>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.6. User who is a citizen of the Russian Federation agrees that due to the aggressive policy of this State and the imposition of appropriate international sanctions on it and the Russian Federation's ranking as a high-risk country for illegal financial transactions, he will have to make an insurance contribution to the account provided by the exchange. The same rule is introduced for User-s from another high-resked countries for illegal financial transactions.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.6.1. The insurance payment will be returned to the User's account within 14 days if there is no data on the commission of any actions that violate the terms of this Agreement, the norms of international law, the customs of honest financial and information turnover.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.6.1. The insurance payment will be returned to the User's account within 14 days if there is no data on the commission of any actions that violate the terms of this Agreement, the norms of international law, the customs of honest financial and information turnover.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.7. User agrees that it will not be able to carry out over-the-counter.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.8 Users, who didn't make a deposit, but received their funds from another account, should buy premium account in case, if they received more then 0.5 BTC from one User. This rule applies to those, who is registered earlier than 1 month. After one month passed, if premium account isn't connected, all new funds, if it is received from another account, will be available for withdrawing, but those funds, which was received during time, when term of registration was less, than 1 month, will be frozen until User don't connect premium account or make an insurance payment.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">12.9 Deposit for purchasing premium status and insurance payment should be done by one payment.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">13. SECURED DEAL</span></p>
<p><span style="background-color: #900909;"><span style="box-sizing: border-box; font-weight: bolder; font-size: 16px; color: #d3d3d3; font-family: 'Open Sans'; background-color: #900909;">13.1. Secured Deal - a service for exchanging of digital and tangible goods and services between Users in a secure way.</span></span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">13.1.1. The essence of this service is that Buyer provides the Seller with the funds under a password, after which the Seller provides the declared service or goods. After Buyer receives the product or service in full, the Buyer informs the Seller of the password for these funds, after which the Seller receives the right to dispose of these funds in full.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">13.1.2. Protecting a Secured Deal</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">13.1.2.1. The protection of a Secure Deal is ensured by the possibility of establishing a three-way conference with the seller, buyer and administrator, who is obliged to monitor the observance of mutual rights and obligations by all parties to the transaction.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">13.1.2.2. In order to protect the rights of our Users, it is also possible to open a dispute, where the administrator will act as an arbitrator. Administrator is obliged to evaluate all the arguments of first and second parties impartially in order to determine the solution of the dispute.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">13.1.3. In order to make a secure purchase transaction, one of the Parties must create a conference with administrator. Then one of the Parties shall make an application on the form below. You need to inform such parameters of transaction as:</span></p>
<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: 'Open Sans'; font-size: 14.4px;">
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">The good or service to be provided to the Customer with a complete and comprehensive description of item and its condition.</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">Price of this product or service.</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">The period within which the Seller is obliged to provide the goods or services to the Buyer. If this is a tangible commodity and will be sent by postal services or transport companies - responsibility for compliance with the deadlines is vested in the transport company, the opening of disputes on this fact will not have consequences, except in the case if the Seller knowingly indicated incorrect data, or otherwise interfered with the correct operation of the transport company or postal service.</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">After the application has been made to the tripartite conference, the second second, which did not prepare the application, must fully agree to the terms and conditions specified in the application.</span></li>
</ul>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">13.1.4. Disputes in Secured Deal.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">13.1.4.1 If the Parties fail to comply with the conditions specified in the application, the Party whose rights have been violated has the right to open a dispute. In connection with the decisions of te arbitrator (administrator), the agreed amount may be withdrawn from the Seller's account in favour of the buyer in order to ensure his financial security in accordance with the rules of our exchange. If the goods have caused moral, material or any other damage to the buyer, the arbitrator shall not be entitled to withdraw from the Seller's account the amount of damage claimed by the Buyer, as this is contrary to the policy of our exchange.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">14. WARRANTIES</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">14.1. Neither https://ucryptocash.com nor its affiliates make any specific promises about functioning of the Site and/or System. For example, https://ucryptocash.com does not make any commitments about the content of the Site, the specific functions of the System, or their reliability, availability or ability to meet the User&rsquo;s needs. https://ucryptocash.com provides the Site and System "AS IS".</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">14.2. To the extent permitted by law https://ucryptocash.com excludes all warranties, guarantees, conditions, representations, and undertakings.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">15. LIMITATION OF LIABILITY</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">15.1. To the extent permitted by law neither https://ucryptocash.com nor https://ucryptocash.com' affiliates, and https://ucryptocash.com' suppliers and distributors will be responsible for lost profits, revenues, financial losses, indirect, special, consequential, exemplary damages.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">15.2. To the extent permitted by law the total amount of https://ucryptocash.com liability, its affiliates, and https://ucryptocash.com'S suppliers and distributors is limited to the amount you paid to https://ucryptocash.com for all Services provided during 3 (three) months prior to the event giving rise to the liability.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">15.3. https://ucryptocash.com, its affiliates, and https://ucryptocash.com'S suppliers and distributors will not be liable for any expense, loss or damage that is not reasonably foreseeable.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">16. INDEMNIFICATION</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">16.1. The User agrees to defend, indemnify and hold https://ucryptocash.com, its affiliates and their respective employees, officers, directors and stockholders harmless from and against any and all damages claimed by a third party as a result of actions by User in violation of this Agreement. The User agrees to defend, indemnify and hold https://ucryptocash.com, its affiliates and their respective employees, officers, directors and stockholders harmless from and against any and all damages for damages to property, bodily injury, death, or other injuries arising from the negligence or misconduct of the User or any person for whom User is legally responsible.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">16.2. The party seeking indemnification in any case shall promptly give written notice to the other of the claim for which indemnification is sought and shall cooperate with the other party in the defense of such an action or suit. The failure to give or delay in giving any such notice shall not limit the indemnifying party's rights hereunder except to the extent it is prejudiced thereby. The indemnifying party shall have the right, at its expense, to direct any such legal proceeding and the negotiation and settlement of any such claim or demand. The indemnifying party shall have no liability for any settlement made without its consent or for any fees or expenses incurred by the other party after the indemnifying party begins directing the legal proceeding.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">17. DISPUTE SETTLEMENT</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">17.1. The Parties will tend to solve all disputes, differences and claims that can arise out of the execution, termination or cancellation of the Agreement by means of negotiations. The Party that has some claims should send a notification to the other Party describing the arisen claims and/or differences.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">17.2. The Party in default on its obligations hereunder shall promptly cure the breach and take due measures to eliminate the consequences. Any dispute arising out of or in connection with this Agreement (including a dispute regarding the existence, validity or termination of this Agreement or the consequences of its nullity) shall be referred to and finally resolved by arbitration under the Arbitration Rules of the London Court of International Arbitration.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">17.3. If any dispute occurs as to the performance or interpretation of the present Agreement that cannot be resolved amicably or in arbitration the Company is entitled to demand the dispute be settled by the Court in location where the https://ucryptocash.com resides.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">18. AMENDMENTS OF THE AGREEMENT</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">18.1. The Service has the right to unilaterally change the terms of the Agreement, Privacy Policy, Anti-Money Laundering Policy and the Fees. The changes take effect 3 (three) days after the moment the new version of corresponding documents is published.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">18.2. At each successive visit to the Site and before starting the use of the Personal Cabinet the User commits to become familiar with the new version of the Agreement, Privacy Policy, Anti-Money Laundering Policy and the Fees. If the User continues to use the Site and the System it will mean that he/she agrees with new versions of the corresponding documents.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">18.3. If the User does not accept new terms of the Agreement, Privacy Policy, Anti-Money Laundering Policy and the Fees, he/she should stop using the Site having closed the Deals with other Users.</span></p>
<p class="h5" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; font-weight: bold; line-height: 1.2; font-size: 20px; color: #ffffff; font-family: 'Open Sans';"><span style="background-color: #900909;">19. CONCLUDING PROVISIONS</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">19.1. With the exception to the cases defined by the Agreement and the current legislation, all the notifications, messages and documents related to the fulfillment of obligations arised out of the Agreement should be sent to and are considered as received by the Parties if they have been sent via email from the authorized address of one Party to the authorized address of the other Party. An authorized address can be:</span></p>
<ul style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: #212529; font-family: 'Open Sans'; font-size: 14.4px;">
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">for the User: the email address indicated in the User Personal Cabinet;</span></li>
<li style="box-sizing: border-box; color: #ffffff; list-style: inherit; margin-bottom: 5px; margin-left: 35px;"><span style="background-color: #900909;">for the https://ucryptocash.com:&nbsp;<a class="link" style="box-sizing: border-box; color: #5b6291; text-decoration-line: none; background-color: #900909;" href="../../terms-and-conditions">support{{ config('app.url') }}.com.</a></span></li>
</ul>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">19.2. The https://ucryptocash.com and all legal relations concerning it are regulated by the legislation of the UK without taking into account its conflict rules. All the arisen disputes are solved according to the legislation of the UK.</span></p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 20px; color: #ffffff; font-family: 'Open Sans'; font-size: 14.4px;"><span style="background-color: #900909;">19.3. If any clause of the Agreement is found void and unenforceable by a court decision, it will not affect the validity of other clauses of the Agreement, which shall remain valid and enforceable.</span></p>
STARTTEXT
,

    \App\Models\Setting::WITHDRAW_MESSAGE =><<<STARTTEXT
Your withdraw request is created! Support will process it within 1-2 days.
STARTTEXT
,

    \App\Models\Setting::TRADING_MESSAGE =><<<STARTTEXT
<p style="line-height: 1.2;">Your trading account is not activated.</p>
<p style="line-height: 1.2;">Unfortunately, you can't use Trading.</p>
<p style="line-height: 1.2;">To start trade you need to buy a Premium Status for your account. More information you can get from support managers or read in Terms and Conditions.</p>
STARTTEXT
,

    \App\Models\Setting::MINIMUM_DEPOSIT_AMOUNT => 0.01,
    \App\Models\Setting::MINIMUM_WITHDRAW_AMOUNT => 0.01,
    \App\Models\Setting::MINIMUM_TRANSFER_AMOUNT => 0.01,
    \App\Models\Setting::TRANSFER_COMMISSION => 10,

    \App\Models\Setting::SECURED_DEAL_WARNING =><<<STARTTEXT
<p class="text-center text-white font-weight-bold mb-0" style="box-sizing: border-box; margin-top: 0px; font-family: 'Open Sans'; font-size: 16px; background-color: #3b151a; margin-bottom: 0px !important; text-align: center !important; font-weight: 700 !important; color: #ffffff !important;">What is it and how to use it?</p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgba(255, 255, 255, 0.5); font-family: 'Open Sans'; font-size: 16px; background-color: #3b151a;">Secured Deal it is perfect way to make a deals with minimal risks. You can buy and sell any goods with maximal safety, because your funds is protected by our rules. The Buyer will send funds, which is protected by password, until all liabilities will be fulfilled. After that Buyer should give password from this funds, and after this the amount of Secured Deal will be added to Seller's account.</p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgba(255, 255, 255, 0.5); font-family: 'Open Sans'; font-size: 16px; background-color: #3b151a;">When you are creating a Secured Deal request or accepting somebody's request of Secured Deal - you accept our rules, which is written in section №13 User Agreement. When Secured Deal is created it appears chat with two Parties of Secured Deal and administrator, who will control your deal from the start to the ending of it. If one of Parties will not follow conditions, which is written in Secured Deal request - funds will be frozen, and after decision of administrator will be returned to Partie.</p>
<p style="box-sizing: border-box; margin-top: 0px; margin-bottom: 1rem; color: rgba(255, 255, 255, 0.5); font-family: 'Open Sans'; font-size: 16px; background-color: #3b151a;">We advise you to make all Deals with cryptocurrency exchanges between Users using this service to protect your funds.</p>
STARTTEXT,
    \App\Models\Setting::CONTACT_US_HEADER => <<<STARTTEXT
STARTTEXT,
    \App\Models\Setting::CONTACT_US_TEXT => <<<STARTTEXT
STARTTEXT,
    \App\Models\Setting::PAYMENT_HEADER => <<<STARTTEXT
STARTTEXT,
    \App\Models\Setting::PAYMENT_TEXT => <<<STARTTEXT
STARTTEXT
];
